### ISSUE TITLE
Feedreader Decsync using flatpak doesnt work

### ISSUE THREAD

**Issue by ghost** [39aldo39/FeedReader#1]

**Comment by 39aldo39** [comment]
What exactly doesn't work?

I did notice that the default DecSync directory is places in some obscure flatpak directory, and the app has no access to other directories. I created jangernert#820 to fix this.

**Comment by ghost** [comment]
Yeah thats the issue i was having, setting it to any other folder traps the data in the sandbox, preventing syncing, ill subscribe to that issue you made

**Comment by ghost** [comment]
For posterity, until the issue is fixed, this can temporarily be resolved by running the following in a terminal

flatpak override org.gnome.FeedReader --user  --filesystem=~/.local/share/decsync
flatpak override org.gnome.FeedReader --user  --env=DECSYNC_DIR=.local/share/decsync

Then feedreader will have access to that folder and it can be synced with syncthing

**Comment by STPKITT** [comment]
Since this still doesn't work for me I wonder is the flatpak not up to date? Searching for Feedreader on flathub.org give zero results even.

**Comment by STPKITT** [comment]
Since this still doesn't work for me I wonder is the flatpak not up to date? Searching for Feedreader on flathub.org give zero results even.

**Comment by STPKITT** [comment]
Since this still doesn't work for me I wonder is the flatpak not up to date? Searching for Feedreader on flathub.org give zero results even.

**Comment by STPKITT** [comment]
Since this still doesn't work for me I wonder is the flatpak not up to date? Searching for Feedreader on flathub.org give zero results even.

**Comment by STPKITT** [comment]
Since this still doesn't work for me I wonder is the flatpak not up to date? Searching for Feedreader on flathub.org give zero results even.

**Comment by STPKITT** [comment]
Since this still doesn't work for me I wonder is the flatpak not up to date? Searching for Feedreader on flathub.org give zero results even.

**Comment by STPKITT** [comment]
Since this still doesn't work for me I wonder is the flatpak not up to date? Searching for Feedreader on flathub.org give zero results even.

**Comment by 39aldo39** [comment]
The original [jangernert/FeedReader](https://github.com/jangernert/FeedReader) is archived and isn't available on Flathub. It might still be available as a package in some distributions, and it can be built from source.

My fork [39aldo39/FeedReader](https://github.com/39aldo39/FeedReader) is the same as the original, but it updates the DecSync plugin. Currently, it has to be built from source. The original version still works, but it won't work for a new DecSync version.

**Comment by STPKITT** [comment]
Thanks for your reply. I had tried building from source but sadly building on a Ubuntu 20.04 isn't possible since a required prequisite, IIRC ninja-build, isn't available. Therefor I looked for a flatpak of FeedReader.
Would FeedReader with Decsync work on an ARM device like the PineTab btw?

**Comment by 39aldo39** [comment]
I see, I have updated the build instructions as there was one wrong dependency. Could you try building again? Please let me know any issues you might have.

It doesn't work right know on ARM devices, but I think it should be possible to make it work with a few small changes.

**Comment by STPKITT** [comment]
Thank you very much, I just built and installed it successfully on Ubuntu 20.04-based KDE neon.
I'll need to try later if the synching works.

I'm not a fan of ARM devices at all but supporting it would come in handy for devices like the PinePhone, PineTab and Librem5 to bring those mobile Linux devices closer to daily driver functionality.
