### ISSUE TITLE
crash when trying to update feeds

### ISSUE THREAD

**Issue by u6aab** [39aldo39/FeedReader#4]
i'm on fedora 35 kde, I just built feedreader and when I select the correct folder it brings up all the correct feeds, but crashes when I try and update. I get this message if I start it from the terminal:

DecSync: Execute all new entries
Uncaught Kotlin exception: kotlin.native.IncorrectDereferenceException: Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread
    at  (0x7f5551297fba)
    at  (0x7f555132989e)
    at  (0x7f555134194f)
    at decsync_so_execute_all_new_entries (0x7f55513d383b)
    at  (0x7f55602cc999)
    at  (0x7f55602d411a)
    at feed_reader_feed_server_interface_getArticles (0x7f557af9e3ca)
    at feed_reader_feed_server_getArticles (0x7f557af9bb3c)
    at feed_reader_feed_server_syncContent (0x7f557af93993)
    at  (0x7f557af7b82b)
    at  (0x7f557af7a965)
    at  (0x7f557af7a980)
    at  (0x7f557af85309)
    at  (0x7f557af85390)
    at  (0x7f557adc7122)
    at  (0x7f557a771ad7)
    at  (0x7f557a7f6770)
    at  ((nil))
An error occured (SIGABRT) in build/../src/Backend/FeedServerInterface.vala, line 129 in 'feed_reader_feed_server_interface_getArticles'
   The reason is likely a failed assertion (assert...).

    #1                                                   line    ? in 'raise'
        at :?
    #2                                                   line    ? in 'abort'
        at :?
    #3  <unknown>                                                   in 'decsync_so_execute_all_new_entries'
        at 
 *  #4  build/../src/Backend/FeedServerInterface.vala    line  129 in 'feed_reader_feed_server_interface_getArticles'               
        at /home/alex/.decsync/FeedReader/build/../src/Backend/FeedServerInterface.vala:129
    #5  build/../src/Backend/FeedServer.vala             line 1179 in 'feed_reader_feed_server_getArticles'
        at /home/alex/.decsync/FeedReader/build/../src/Backend/FeedServer.vala:1179
    #6  build/../src/Backend/FeedServer.vala             line  262 in 'feed_reader_feed_server_syncContent'
        at /home/alex/.decsync/FeedReader/build/../src/Backend/FeedServer.vala:262

**Comment by 39aldo39** [comment]
Thanks for the report! Apparently I introduced the crash in libdecsync without noticing. A workaround is to use the old version v2.1.2 (execute `git switch -d v2.1.2` before compiling libdecsync).

**Comment by u6aab** [comment]
thanks, that worked. a note for anybody else who does this, make sure to uninstall libdecsync before building 2.1.2 because otherwise it seems to keep the newer bugged version

**Comment by 39aldo39** [comment]
I now also fixed the bug in the latest version!
